name: Deploy via rsync to Mittwald webspace
on:
  push:
    branches:
      - master
   
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    # Replace with your preferred runner tag if needed
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Test secrets...
        run: echo TEST
    
      - name: Checkout Branch
        uses: actions/checkout@v2

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SERVER_REMOTE_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy with rsync
        run: rsync -avz --progress --exclude 'vcard/assets' /home/runner/work/vcard/vcard ${{ secrets.SERVER_REMOTE_USER}}@${{ secrets.SERVER_REMOTE_HOST }}:${{ secrets.SERVER_REMOTE_TARGET }}
